Update testing/log-making system.
This is a bit more complex than I'd like, but it works.

Any new test that cares about the compiler settings (even if only
because that makes a difference to the log output) should have an entry
in index.aux, and also a testXXX.aux file to skip the test when the
compiler settings aren't appropriate. The index.aux entry is used as a
default when running the test, and is also used by the Makefile to
generate the golden log.

The prelude tests work a bit differently. See index.aux and prelude.aux
for examples. If any prelude test fails, `run-tests -f` will re-run all
of the prelude tests. It seemed too complicated to try anything smarter.

diff --git a/contrib/run-tests.in b/contrib/run-tests.in
--- a/contrib/run-tests.in
+++ b/contrib/run-tests.in
@@ -67,11 +67,33 @@ pathops()
   esac
 }
 
-# if running all tests, or failed
+run1()
+{
+    trap 'x=$?; rm -f '$tmp'; exit $x;' ALRM HUP INT TERM
+    if ./run-test ${pufs} < "$t" 2>&1 | ${DIFF} -u "$log" - > "$tmp"
+    then
+      rm -f "$tmp" "$diff"
+      echo "${ECHO_T}passed"
+    else
+      rc=1
+      mv "$tmp" "$diff"
+      echo "${ECHO_T}FAILED"
+    fi
+}
+
+autoprelude=0
+
+# if running all tests, or -f
 if test 0 -eq $#; then
+  # if running all tests, or prelude has a *.diff
+  if test 0 -eq $failed || test -n "$(echo "$outdir/prelude"*.diff)"; then
+    tests="$srcdir/lib/prelude.pure"
+    autoprelude=1
+  else
   tests=
-  for s in "$srcdir/lib/prelude.pure" $(find "$testdir" -name test\*.pure | sort); do
-    # if running all tests, or this has a *.diff, add to list
+  fi
+  for s in $(find "$testdir" -name test\*.pure | sort); do
+    # if running all tests, or this has a *.diff
     if test 0 -eq $failed || test -e $(pathops -d "$s"); then
       tests="$tests $s"
     fi
@@ -85,10 +107,14 @@ echo Running tests.
 
 test -d "$outdir" || mkdir -p "$outdir"
 
-# The prelude.aux script should test compiler settings and print to stdout
-# a string like "prelude-foo". In that case, requesting a test of lib/prelude.pure
-# will compare against the logfile test/prelude-foo.log.
-# Scripts like test015.aux should test compiler settings and exit with a nonzero
+# * The prelude.aux script should test compiler settings and print to stdout
+#   a string like "prelude-foo". In that case, requesting a test of
+#   lib/prelude.pure will compare against the logfile test/prelude-foo.log.
+#
+# * The index.aux file specifies what compiler settings each test script should
+#   be run with by default; this is overridden by any settings in PURE_FLAGS.
+#
+# * Scripts like test015.aux should test compiler settings and exit with a nonzero
 # status to skip running the related test. For example:
 #  ### test015.aux ###
 #  #! --if trees23
@@ -98,26 +124,28 @@ test -d "$outdir" || mkdir -p "$outdir"
 
 for t in "$@"; do
   pathops -A "$t"
-  pufs="$PURE_FLAGS"
+  if test prelude = "$bname" && test 1 -eq $autoprelude; then
+    for log in $(find "$testdir" -name prelude\*.log | sort); do
+      fname="${log##*/}"
+      bname="${fname%.*}"
+      diff="$outdir/$bname.diff"
+      tmp="$diff.$$"
+      pufs=$(awk -F: -v"base=$bname" '$1==base {print $2}' "$testdir/index.aux")
+      echo ${ECHO_N} "$(echo prelude.pure $pufs $PURE_FLAGS): ${ECHO_C}"
+      pufs="$pufs $PURE_FLAGS -n"
+      run1
+    done
+  else
   echo ${ECHO_N} "$fname: ${ECHO_C}"
-  if test "x$bname" = "xprelude"
-  then
+    pufs="$(awk -F: -v"base=$bname" '$1==base {print $2}' "$testdir/index.aux") $PURE_FLAGS"
+    if test prelude = "$bname"; then
     log="$testdir/$(level=0 ./run-test ${pufs} "$testdir/prelude.aux").log"
     pufs="$pufs -n"
-  elif test -e "$aux" && ! level=0 ./run-test ${pufs} "$aux" >/dev/null
-  then
+    elif test -e "$aux" && ! level=0 ./run-test ${pufs} "$aux" >/dev/null; then
     echo "${ECHO_T}skipped"
     continue
   fi
-  trap 'x=$?; rm -f '$tmp'; exit $x;' ALRM HUP INT TERM
-  if ./run-test ${pufs} < "$t" 2>&1 | ${DIFF} -u "$log" - > "$tmp"
-  then
-    rm -f "$tmp" "$diff"
-    echo "${ECHO_T}passed"
-  else
-    rc=1
-    mv "$tmp" "$diff"
-    echo "${ECHO_T}FAILED"
+    run1
   fi
 done
 
